# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [3]:
import numpy as pnp
import pandas as pd

### Step 2. Import the dataset from this [address](https://github.com/guipsamora/pandas_exercises/blob/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

In [12]:
url= "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv"

### Step 3. Assign it to a variable called df.

In [14]:
df= pd.read_csv(url,sep=',')
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
366,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,13,13,13
367,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,7,6,0
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
369,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,10,14,12,11
370,MS,F,19,U,LE3,T,3,2,services,services,...,3,2,2,1,1,3,4,7,7,9
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
374,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,19,18,19
375,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,2,8,8,10
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
377,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,4,8,9,10
378,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,0,15,15,15
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14
381,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,5,7,6,7
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
383,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,6,5,0
384,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,14,6,5,5
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,0,7,9,8
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [15]:
df.columns

Index([u'school', u'sex', u'age', u'address', u'famsize', u'Pstatus', u'Medu',
       u'Fedu', u'Mjob', u'Fjob', u'reason', u'guardian', u'traveltime',
       u'studytime', u'failures', u'schoolsup', u'famsup', u'paid',
       u'activities', u'nursery', u'higher', u'internet', u'romantic',
       u'famrel', u'freetime', u'goout', u'Dalc', u'Walc', u'health',
       u'absences', u'G1', u'G2', u'G3'],
      dtype='object')

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [55]:
df_sliced=df.loc[:,"school":"guardian"]
df_sliced

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father
12,GP,M,15,U,LE3,T,4,4,health,services,course,father
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother
14,GP,M,15,U,GT3,A,2,2,other,other,home,other
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother
19,GP,M,16,U,LE3,T,4,3,health,other,home,father
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother
21,GP,M,15,U,GT3,T,4,4,health,health,other,father
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother
...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother
366,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother
367,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother
368,MS,F,18,U,GT3,T,2,3,at_home,services,course,father
369,MS,F,18,R,GT3,T,4,4,other,teacher,other,father
370,MS,F,19,U,LE3,T,3,2,services,services,home,other
371,MS,M,18,R,LE3,T,1,2,at_home,services,other,father
372,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother
373,MS,F,17,R,GT3,T,1,2,other,other,course,mother
374,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother
375,MS,F,18,R,GT3,T,1,1,other,other,home,mother
376,MS,F,20,U,GT3,T,4,2,health,other,course,other
377,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother
378,MS,F,18,U,GT3,T,3,3,other,other,home,mother
379,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father
381,MS,M,18,R,GT3,T,2,1,other,other,other,mother
382,MS,M,17,U,GT3,T,2,3,other,services,home,father
383,MS,M,19,R,GT3,T,1,1,other,services,other,mother
384,MS,M,18,R,GT3,T,4,2,other,other,home,father
385,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother
387,MS,F,19,R,GT3,T,2,3,services,other,course,mother
388,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother
389,MS,F,18,U,GT3,T,1,1,other,other,course,mother
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that captalize strings.

In [56]:
#lambda que recibe u parametro y lo combierte en upper
cap= lambda x: x.upper()
df_sliced['Mjob'].apply(cap)

0       AT_HOME
1       AT_HOME
2       AT_HOME
3        HEALTH
4         OTHER
5      SERVICES
6         OTHER
7         OTHER
8      SERVICES
9         OTHER
10      TEACHER
11     SERVICES
12       HEALTH
13      TEACHER
14        OTHER
15       HEALTH
16     SERVICES
17        OTHER
18     SERVICES
19       HEALTH
20      TEACHER
21       HEALTH
22      TEACHER
23        OTHER
24     SERVICES
25     SERVICES
26        OTHER
27       HEALTH
28     SERVICES
29      TEACHER
         ...
365     AT_HOME
366     TEACHER
367       OTHER
368     AT_HOME
369       OTHER
370    SERVICES
371     AT_HOME
372       OTHER
373       OTHER
374       OTHER
375       OTHER
376      HEALTH
377     TEACHER
378       OTHER
379     AT_HOME
380     TEACHER
381       OTHER
382       OTHER
383       OTHER
384       OTHER
385     AT_HOME
386     TEACHER
387    SERVICES
388     TEACHER
389       OTHER
390    SERVICES
391    SERVICES
392       OTHER
393    SERVICES
394       OTHER
Name: Mjob, Length: 395, dtype: object

### Step 6. Capitalize both Mjob and Fjob

In [57]:
df_sliced.Mjob.apply(cap)
df_sliced.Fjob.apply(cap)

0       TEACHER
1         OTHER
2         OTHER
3      SERVICES
4         OTHER
5         OTHER
6         OTHER
7       TEACHER
8         OTHER
9         OTHER
10       HEALTH
11        OTHER
12     SERVICES
13        OTHER
14        OTHER
15        OTHER
16     SERVICES
17        OTHER
18     SERVICES
19        OTHER
20        OTHER
21       HEALTH
22        OTHER
23        OTHER
24       HEALTH
25     SERVICES
26        OTHER
27     SERVICES
28        OTHER
29      TEACHER
         ...
365       OTHER
366    SERVICES
367    SERVICES
368    SERVICES
369     TEACHER
370    SERVICES
371    SERVICES
372     AT_HOME
373       OTHER
374       OTHER
375       OTHER
376       OTHER
377    SERVICES
378       OTHER
379       OTHER
380     TEACHER
381       OTHER
382    SERVICES
383    SERVICES
384       OTHER
385       OTHER
386     AT_HOME
387       OTHER
388    SERVICES
389       OTHER
390    SERVICES
391    SERVICES
392       OTHER
393       OTHER
394     AT_HOME
Name: Fjob, Length: 395, dtype: object

### Step 7. Print the last elements of the data set.

In [59]:
df_sliced.tail(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and captalize Mjob and Fjob.

In [ ]:
df_sliced['Mjob']=df_sliced.Mjob.apply(cap)
df_sliced.['Fjob'].apply(cap)

### Step 9. Create a function called majority that return a boolean value to a new column called legal_drinker

In [60]:
df_sliced['legal_drinker'] = df['Pstatus'].str.contains('A')
df_sliced

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,True
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,False
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,False
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,False
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,False
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother,False
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,True
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother,True
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother,False
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother,False
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father,False
12,GP,M,15,U,LE3,T,4,4,health,services,course,father,False
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother,False
14,GP,M,15,U,GT3,A,2,2,other,other,home,other,True
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother,False
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother,False
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother,False
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother,False
19,GP,M,16,U,LE3,T,4,3,health,other,home,father,False
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother,False
21,GP,M,15,U,GT3,T,4,4,health,health,other,father,False
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother,False
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother,False
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother,False
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother,False
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother,False
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother,False
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother,True
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother,False
366,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother,False
367,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother,False
368,MS,F,18,U,GT3,T,2,3,at_home,services,course,father,False
369,MS,F,18,R,GT3,T,4,4,other,teacher,other,father,False
370,MS,F,19,U,LE3,T,3,2,services,services,home,other,False
371,MS,M,18,R,LE3,T,1,2,at_home,services,other,father,False
372,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother,False
373,MS,F,17,R,GT3,T,1,2,other,other,course,mother,False
374,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother,False
375,MS,F,18,R,GT3,T,1,1,other,other,home,mother,False
376,MS,F,20,U,GT3,T,4,2,health,other,course,other,False
377,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother,False
378,MS,F,18,U,GT3,T,3,3,other,other,home,mother,False
379,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother,False
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father,False
381,MS,M,18,R,GT3,T,2,1,other,other,other,mother,False
382,MS,M,17,U,GT3,T,2,3,other,services,home,father,False
383,MS,M,19,R,GT3,T,1,1,other,services,other,mother,False
384,MS,M,18,R,GT3,T,4,2,other,other,home,father,False
385,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother,False
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother,False
387,MS,F,19,R,GT3,T,2,3,services,other,course,mother,False
388,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother,False
389,MS,F,18,U,GT3,T,1,1,other,other,course,mother,False
390,MS,M,20,U,LE3,A,2,2,services,services,course,other,True
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother,False
392,MS,M,21,R,GT3,T,1,1,other,other,course,other,False
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother,False
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father,False

In [64]:
majority= lambda x: True if x>19 else False

In [66]:
df_sliced['Majority']= df_sliced['age'].apply(majority)
df_sliced

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker,Majority
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,True,False
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,False,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,False,False
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,False,False
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,False,False
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,False,False
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother,False,False
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,True,False
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother,True,False
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother,False,False
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother,False,False
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father,False,False
12,GP,M,15,U,LE3,T,4,4,health,services,course,father,False,False
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother,False,False
14,GP,M,15,U,GT3,A,2,2,other,other,home,other,True,False
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother,False,False
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother,False,False
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother,False,False
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother,False,False
19,GP,M,16,U,LE3,T,4,3,health,other,home,father,False,False
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother,False,False
21,GP,M,15,U,GT3,T,4,4,health,health,other,father,False,False
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother,False,False
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother,False,False
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother,False,False
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother,False,False
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother,False,False
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother,False,False
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother,True,False
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother,False,False
366,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother,False,False
367,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother,False,False
368,MS,F,18,U,GT3,T,2,3,at_home,services,course,father,False,False
369,MS,F,18,R,GT3,T,4,4,other,teacher,other,father,False,False
370,MS,F,19,U,LE3,T,3,2,services,services,home,other,False,False
371,MS,M,18,R,LE3,T,1,2,at_home,services,other,father,False,False
372,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother,False,False
373,MS,F,17,R,GT3,T,1,2,other,other,course,mother,False,False
374,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother,False,False
375,MS,F,18,R,GT3,T,1,1,other,other,home,mother,False,False
376,MS,F,20,U,GT3,T,4,2,health,other,course,other,False,True
377,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother,False,False
378,MS,F,18,U,GT3,T,3,3,other,other,home,mother,False,False
379,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother,False,False
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father,False,False
381,MS,M,18,R,GT3,T,2,1,other,other,other,mother,False,False
382,MS,M,17,U,GT3,T,2,3,other,services,home,father,False,False
383,MS,M,19,R,GT3,T,1,1,other,services,other,mother,False,False
384,MS,M,18,R,GT3,T,4,2,other,other,home,father,False,False
385,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother,False,False
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother,False,False
387,MS,F,19,R,GT3,T,2,3,services,other,course,mother,False,False
388,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother,False,False
389,MS,F,18,U,GT3,T,1,1,other,other,course,mother,False,False
390,MS,M,20,U,LE3,A,2,2,services,services,course,other,True,True
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother,False,False
392,MS,M,21,R,GT3,T,1,1,other,other,course,other,False,True
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother,False,False
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father,False,False

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [ ]:
def multbyten(x):
    if type(x) is str:
        return x
    elif type(x) is np.int64